name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git ffmpeg libswresample-dev libavfilter-dev \
            libavdevice-dev libavcodec-dev libavformat-dev libpostproc-dev \
            python3-pip python3-setuptools libffi-dev libssl-dev \
            autoconf automake libtool pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev libtinfo5 cmake zip unzip

      - name: Install Buildozer and Cython
        run: |
          pip3 install --user --upgrade pip
          # Cython 3.0+ ломает сборку Kivy, используем проверенную ветку 0.29.x
          pip3 install --user "cython<3.0.0" buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build with Buildozer
        run: |
          # --yes автоматически принимает все лицензии Android SDK
          buildozer -v android debug
        env:
          # Это поможет избежать некоторых ошибок с кодировкой в логах
          PYTHONIOENCODING: utf-8

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: KKT-Scanner-Debug
          path: bin/*.apk
