name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Это действие само установит нужные версии Python, Cython и Buildozer
      - name: Buildozer Action
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_version: master
          # Мы указываем собирать только android debug
          command: buildozer android debug
          # Это позволит кешировать SDK/NDK, чтобы сборка шла быстрее в следующий раз
          repository_display_name: KKT-Scanner

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: KKT-Scanner-Package
          path: bin/*.apk
