name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
        # 1. Загрузка кода
      - uses: actions/checkout@v3

        # 2. Установка Java 17 (необходима для Android API 33)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

        # 3. Установка системных зависимостей для Buildozer
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git python3-setuptools \
          libncurses5-dev libncursesw5-dev zlib1g-dev libffi-dev libssl-dev \
          autoconf automake libtool pkg-config patch

        # 4. Установка Buildozer и Cython
      - name: Install Buildozer
        run: pip3 install --user buildozer cython

        # 5. Принятие лицензий Android SDK (решает ошибку Broken pipe)
      - name: Accept Android Licenses
        run: |
          yes | sdkmanager --licenses || true

        # 6. Сборка APK
      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          buildozer -v android debug

        # 7. Сохранение готового APK в артефакты GitHub
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: bin/*.apk
